core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>', views.category, name='category'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm, extra_context={'show_login': True, 'show_tab': False, 'asdad21213': True, 'zxcasdawd': 'target-element'}), name='login'),
    path('logout/', views.log_out, name='logout'),
    path('all_staff/', views.all_staff, name='all_staff')
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>', views.detail, name='detail'),
    path('', views.items, name='items'),
    path('<int:pk>/add', views.add, name='add'),
    path('<int:pk>/remove', views.remove, name='remove'),
    path('<int:pk>/remove_detail', views.remove_detail, name='remove_detail'),
    path('basket/', views.basket, name='basket'),
    path('gender/<str:gender>', views.gender_f, name='gender'),
    path('<str:gender>/<int:pk>', views.gender_detail_f, name='gender_detail'),
    path('delete', views.delete, name='delete'),
    path('purchase', views.purchase, name='purchase'),
    path('<int:pk>/purchase_delete', views.purchase_delete, name='purchase_delete'),
    path('<int:pk>/purchase_delete_admin', views.purchase_delete_admin, name='purchase_delete_admin'),
    path('all_purchases', views.all_purchases, name='all_purchases'),
    path('new_category', views.new_category, name='new_category'),
    path('new_item', views.new_item, name='new_item'),
    path('<int:pk>/remove_category', views.remove_category, name='remove_category'),
    path('<int:pk>/remove_item', views.remove_item, name='remove_item'),
    path('<int:pk>/edit_item', views.edit_item, name='edit_item'),
    path('<int:pk>/edit_category', views.edit_category, name='edit_category'),
    path('<int:pk>/new_comment', views.new_comment, name='new_comment'),
    path('<int:pk_comment>/<int:pk_item>/delete_comment', views.delete_comment, name='delete_comment'),
    path('<int:pk_comment>/<int:pk_item>/edit_comment', views.edit_comment, name='edit_comment'),
    path('all_comments', views.all_comments, name='all_comments'),
    path('gender_index/<str:gender>', views.gender_index, name='gender_index'),
    path('gender_detail/<str:gender>/<int:pk>', views.gender_detail, name='gender_detail'),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import google_one_tap_login

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
    path('inbox/', include('conversation.urls')),
    path('google_one_tap_login/', google_one_tap_login, name='google_one_tap_login'),
    path('oauth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-5/6 mx-auto py-4 px-6 rounded-xl dark:text-black'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-5/6 mx-auto py-4 px-6 rounded-xl dark:text-black'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-5/6 mx-auto py-4 px-6 rounded-xl dark:text-black'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-5/6 mx-auto py-4 px-6 rounded-xl dark:text-black'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-5/6 mx-auto  py-4 px-6 rounded-xl dark:text-black',
        'type' : 'password',
        'autocomplete': 'new-password',
        'required': True
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-5/6 mx-auto  py-4 px-6 rounded-xl dark:text-black',
        'type' : 'password',
        'autocomplete': 'new-password',
        'required': True
    }))

core/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User

from django.contrib.auth import logout, login
from item.models import Category, Item
from .forms import SignupForm
import random

from django.conf import settings

from django.shortcuts import redirect
from django.http import JsonResponse
from django.conf import settings
from django.contrib.auth import get_user_model, login
from google.oauth2 import id_token
from google.auth.transport import requests
import json

User = get_user_model()

def google_one_tap_login(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            token = data.get('credential')
            if not token:
                return JsonResponse({'success': False, 'error': 'No credential provided'}, status=400)

            # Verify the token
            try:
                idinfo = id_token.verify_oauth2_token(token, requests.Request(), settings.SOCIAL_AUTH_GOOGLE_OAUTH2_KEY)
                if idinfo['iss'] not in ['accounts.google.com', 'https://accounts.google.com']:
                    return JsonResponse({'success': False, 'error': 'Wrong issuer.'}, status=401)
                
                email = idinfo['email']
                first_name = idinfo.get('given_name', '')
                last_name = idinfo.get('family_name', '')
                username = email.split('@')[0]

                # Find or create a user
                user, created = User.objects.get_or_create(email=email, defaults={
                    'first_name': first_name,
                    'last_name': last_name,
                    'username': username
                })

                # Log the user in with specified backend
                user.backend = 'django.contrib.auth.backends.ModelBackend'  # Замените на правильный backend
                login(request, user)
                return JsonResponse({'success': True, 'redirect_url': settings.LOGIN_REDIRECT_URL})

            except ValueError as e:
                return JsonResponse({'success': False, 'error': str(e)}, status=400)

        except Exception as e:
            return JsonResponse({'success': False, 'error': str(e)}, status=500)
    else:
        return JsonResponse({'success': False, 'error': 'Invalid request method.'}, status=405)


def all_staff(request):
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()

    gender = ''
    if "gender" not in request.session:
        gender = 'ALL'
    else:
        gender = request.session["gender"]

    if gender != 'ALL':
        items = items.filter(gender=gender)

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': sorted(items, key=lambda x: random.random()),
        'name_category' : 'All stuff',
        'gender': gender,
        'show_login': True,
        'ajiogfjdhspgojdsapg': 'xjcvxzklczxkc'
    })

def index(request):
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()

    gender = ''
    if "gender" not in request.session:
        gender = 'ALL'
    else:
        gender = request.session["gender"]

    if gender != 'ALL':
        items = items.filter(gender=gender)

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': sorted(items, key=lambda x: random.random()),
        'name_category' : 'All stuff',
        'gender': gender,
        'show_login': True,
    })



def category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    items = Item.objects.filter(category=category)
    categories = Category.objects.all()

    gender = ''
    if "gender" not in request.session:
        gender = 'ALL'
    else:
        gender = request.session["gender"]

    if gender != 'ALL':
        items = items.filter(gender=gender)

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': sorted(items, key=lambda x: random.random()),
        'name_category' : category.name,
        'gender': gender,
        'query': category,
        'asdad21213': True
    })  


def log_out(request):
    logout(request)
    return redirect('/')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            email = form.cleaned_data['email']
            if User.objects.filter(email=email).exists():
                form.add_error('email', 'email already exists, choose another email or u can auth from google')
            else:
                user = form.save()

                user.backend = 'django.contrib.auth.backends.ModelBackend'
                login(request, user)
                return redirect('/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form,
        'show_login': True,
        'show_tab': False,
        'asdad21213': True,
        'zxcasdawd': 'target-element'
    })

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Dolce Vita Wear{% endblock %}

{% block content %}

    <div class="mt-4 px-4 py-4 bg-gray-100 rounded-xl dark:bg-zinc-500 mx-auto md:w-1/2 transition-transform duration-300 transform hover:scale-105">
        <h2 class="transition-transform duration-300 transform hover:scale-110 mb-4 text-3xl text-center font-semibold dark:text-white"><a href="{% url 'core:all_staff'%}"> All stuff </a></h2>

        <form method="get" action="{% url 'item:items' %}">
                {%if query%}
                    <input name="query" type="text" class="transition-transform duration-300 transform hover:scale-110 form-control md:w-1/2  w-3/4 mx-auto mb-4" autofocus value="{{query}}">
                {%else%}
                    <input name="query" type="text" class="transition-transform duration-300 transform hover:scale-110 form-control md:w-1/2  w-3/4 mx-auto rounded-xl mb-4" autofocus>
                {%endif%}
        </form>
    

        <div class="xcjvxckljvlk grid grid-cols-2 md:grid-cols-4 gap-4">
            {% for category in categories %}
            <div class="transition-transform duration-300 transform hover:scale-125 p-2 bg-white rounded-xl text-center dark:text-black">
                <a href="{% url 'core:category' category.id %}" class="block">
                    <h2 class="text-lg md:text-2xl font-semibold">{{ category.name }}</h2>
                    <p class="text-gray-500 text-sm">{{ category.items.count }} items</p>
                    {% if request.user.is_superuser %}
                        <div class="mt-2">
                            <a href="{% url 'item:remove_category' category.id %}" class="block px-2 py-2 text-sm md:text-lg font-semibold bg-red-500 hover:bg-red-600 text-white rounded-xl mb-1">Remove</a>
                            <a href="{% url 'item:edit_category' category.id %}" class="block px-2 py-2 text-sm md:text-lg font-semibold bg-red-500 hover:bg-red-600 text-white rounded-xl">Edit</a>
                        </div>
                    {% endif %}
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

    <div id="target-element"></div>

    <div id="{{ajiogfjdhspgojdsapg}}"></div>


    <div class="asfafzxcvzd23123 mx-5 mt-20 px-3 md:px-6 md:py-12 py-4 bg-gray-100 rounded-xl dark:bg-zinc-500 transition-transform duration-300 transform hover:scale-105" id="xcvxckjvl123">
        <h2 class="mb-4 mt-2 text-3xl text-center font-bold dark:text-white">{{ name_category }}</h2>

        <div class="blckvlvjvv grid grid-cols-2 md:grid-cols-4 gap-8">
            {% for item in items %}
                <div class="transition-transform duration-300 transform hover:scale-105">
                    <a href="{% url 'item:detail' item.id %}">
                        {% if item.gender == 'W'%}
                            {% if item.image.url %}
                                <img src="{{ item.image.url }}" class="zoom-image rounded-xl object-cover w-full md:h-96 h-60">
                            {% endif %}
                        {% else %}
                            {% if item.image.url %}
                                <img src="{{ item.image.url }}" class="zoom-image rounded-xl object-cover w-full md:h-96 h-60">
                            {% endif %}
                        {% endif %}
                        <div class="cvkxljbxcljkvb p-3 bg-white rounded-b-xl md:text-center text-pretty">
                                {% if item.gender == 'M'%}
                                <h2 class="md:text-3xl text-xl text-blue-700 font-semibold">{{ item.name }}</h2>
                                {% else %}
                                <h2 class="md:text-3xl text-xl text-red-700 font-semibold">{{ item.name }}</h2>
                                {% endif %}
                            <strong><p class="text-xl md:text-3xl font-semibold">{{ item.price }}$</p></strong>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="my-6 mx-auto md:w-1/2 p-2 bg-gray-100 rounded-xl dark:bg-zinc-500 dark:text-white text-center transition-transform duration-300 transform hover:scale-105">
    <h1 class="mt-2 mb-2 text-3xl">Log in</h1>
    <hr class="mb-2 w-1/2 mx-auto">

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-2 bg-red-100 rounded-xl dark:text-black w-5/6 mx-auto mt-2">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="w-1/2 mx-auto text-center m-2 py-2 px-4 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="my-6 mx-auto md:w-1/2 p-2 bg-gray-100 rounded-xl dark:bg-zinc-500 dark:text-white text-center transition-transform duration-300 transform hover:scale-105">
    <h1 class="mt-2 mb-2 text-3xl">Sign up</h1>
    <hr class="mb-3 w-1/2 mx-auto">

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl dark:text-black w-5/6 mx-auto mt-2">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="text-center w-1/2 mx-auto m-2 py-2 px-4 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}