conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>', views.category, name='category'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm, extra_context={'show_login': True, 'show_tab': False, 'asdad21213': True, 'zxcasdawd': 'target-element'}), name='login'),
    path('logout/', views.log_out, name='logout'),
    path('all_staff/', views.all_staff, name='all_staff')
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>', views.detail, name='detail'),
    path('', views.items, name='items'),
    path('<int:pk>/add', views.add, name='add'),
    path('<int:pk>/remove', views.remove, name='remove'),
    path('<int:pk>/remove_detail', views.remove_detail, name='remove_detail'),
    path('basket/', views.basket, name='basket'),
    path('gender/<str:gender>', views.gender_f, name='gender'),
    path('<str:gender>/<int:pk>', views.gender_detail_f, name='gender_detail'),
    path('delete', views.delete, name='delete'),
    path('purchase', views.purchase, name='purchase'),
    path('<int:pk>/purchase_delete', views.purchase_delete, name='purchase_delete'),
    path('<int:pk>/purchase_delete_admin', views.purchase_delete_admin, name='purchase_delete_admin'),
    path('all_purchases', views.all_purchases, name='all_purchases'),
    path('new_category', views.new_category, name='new_category'),
    path('new_item', views.new_item, name='new_item'),
    path('<int:pk>/remove_category', views.remove_category, name='remove_category'),
    path('<int:pk>/remove_item', views.remove_item, name='remove_item'),
    path('<int:pk>/edit_item', views.edit_item, name='edit_item'),
    path('<int:pk>/edit_category', views.edit_category, name='edit_category'),
    path('<int:pk>/new_comment', views.new_comment, name='new_comment'),
    path('<int:pk_comment>/<int:pk_item>/delete_comment', views.delete_comment, name='delete_comment'),
    path('<int:pk_comment>/<int:pk_item>/edit_comment', views.edit_comment, name='edit_comment'),
    path('all_comments', views.all_comments, name='all_comments'),
    path('gender_index/<str:gender>', views.gender_index, name='gender_index'),
    path('gender_detail/<str:gender>/<int:pk>', views.gender_detail, name='gender_detail'),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import google_one_tap_login

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
    path('inbox/', include('conversation.urls')),
    path('google_one_tap_login/', google_one_tap_login, name='google_one_tap_login'),
    path('oauth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
from django.db import models
from django.contrib.auth.models import User

gender_choice = {
    "M": "Man",
    "W": "Woman",
}

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name
    
class Comment(models.Model):
    user = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)
    description = models.TextField()
    created_at = models.DateTimeField()

    class Meta:
        ordering = ('-created_at',)
    

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    users = models.ManyToManyField(User, related_name='items', blank=True)
    gender = models.CharField(max_length=1, choices=gender_choice)
    comments = models.ManyToManyField(Comment)

    def __str__(self):
        return self.name


class Purchase(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(Item)
    telegram = models.CharField(max_length=255)
    price = models.FloatField()           

item/forms.py
from django import forms

from .models import Item, Category, Comment

INPUT_CLASSES = 'block w-full md:w-1/2 md:mx-auto py-4 px-6 rounded-xl border dark:bg-zinc-700 dark:text-white'

class NewCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            })
        }

class NewCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('description',)
        widgets = {
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
        }

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image', 'gender')
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'gender': forms.Select(attrs={
                'class': INPUT_CLASSES
            })
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold', 'gender')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'gender': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
        }


class EditCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            })
        }

item/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse, HttpResponseRedirect

from .models import Category, Item, Purchase, Comment

import random

from datetime import datetime

from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags


from .forms import NewItemForm, NewCategoryForm, EditItemForm, EditCategoryForm, NewCommentForm



def detail(request, pk, operation=None, form=None, pk_comment=None, form_edit=None, op=None, js_op=None, pisya=None):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)

    gender = ''
    if "gender" not in request.session:
        gender = 'ALL'
    else:
        gender = request.session["gender"]

    if gender != 'ALL':
        related_items = related_items.filter(gender=gender)


    if request.user.is_authenticated:
        basket_items = request.user.items.all()
        in_basket = False
        if item in basket_items:
            in_basket = True

        if form == None:
            form = NewCommentForm()
        
        return render(request, 'item/detail.html', {
            'item': item,
            'related_items': related_items,
            'in_basket': in_basket,
            'operation': operation,
            'gender': gender,
            'form': form,
            'edit_form': form_edit,
            'pk_comment': pk_comment,
            'op': op,
            'js_op': js_op,
            'asdad21213': True,
            'zxc12qwiehjqwaiode': 'target-element',
            'xzcqer1e4123': False,
            'pisya': pisya,
            'zxcasjdlqwikjeo1i23' : True
        })

    return render(request, 'item/detail.html', {
            'item': item,
            'related_items': related_items,
            'gender': gender,
            'asdad21213': True,
            'zxcasdawd': 'target-element',
            'xzcqer1e4123': False,
            'zxcasjdlqwikjeo1i23' : True
    })

def items(request):
    query = request.GET.get('query', '')
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    gender = ''
    if "gender" not in request.session:
        gender = 'ALL'
    else:
        gender = request.session["gender"]

    if gender != 'ALL':
        items = items.filter(gender=gender)

    if query:
        items = items.filter(Q(name__contains=query) | Q(description__contains=query) | Q(category__name__contains=query))

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': sorted(items, key=lambda x: random.random()),
        'name_category' : f'{query}' if query else '🪦💀',
        'gender': gender,
        'query': query,
        'asdad21213': True
    })

@login_required
def add(request, pk):
    item = get_object_or_404(Item, pk=pk)
    request.user.items.add(item)
    return detail(request, pk=pk, operation="add", js_op='fgkjsdflkgjdkslfg')

@login_required
def basket(request, message=None):
    items = request.user.items.all()
    purchases = Purchase.objects.filter(user=request.user)

    

    return render(request, 'item/basket.html', {
        'items': items,
        'message': message,
        'purchases': purchases[::-1],
        'asdad21213': True
    })

@login_required
def remove(request, pk):
    item = get_object_or_404(Item, pk=pk)
    request.user.items.remove(item)
    return redirect('item:basket')

@login_required
def remove_detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    request.user.items.remove(item)
    return detail(request, pk=pk, operation="remove", js_op='fgkjsdflkgjdkslfg')


def gender_f(request, gender):
    if "gender" not in request.session:
        request.session["gender"] = ''
    request.session["gender"] = gender
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def gender_index(request, gender):
    if "gender" not in request.session:
        request.session["gender"] = ''
    request.session["gender"] = gender
    
    query = request.GET.get('query', '')
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    gender = ''
    if "gender" not in request.session:
        gender = 'ALL'
    else:
        gender = request.session["gender"]

    if gender != 'ALL':
        items = items.filter(gender=gender)

    if query:
        items = items.filter(Q(name__contains=query) | Q(description__contains=query) | Q(category__name__contains=query))

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': sorted(items, key=lambda x: random.random()),
        'name_category' : f'{query}' if query else '🪦💀',
        'gender': gender,
        'query': query,
        'asdad21213': True,
        'asdzxczxczxc123': True
    })

def gender_detail(request, gender, pk):
    if "gender" not in request.session:
        request.session["gender"] = ''
    request.session["gender"] = gender

    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)

    gender = ''
    if "gender" not in request.session:
        gender = 'ALL'
    else:
        gender = request.session["gender"]

    if gender != 'ALL':
        related_items = related_items.filter(gender=gender)

    
    return render(request, 'item/detail.html', {
            'item': item,
            'related_items': related_items,
            'gender': gender,
            'asdad21213': True,
            'zxcasdawd': 'target-element',
            'xzcqer1e4123': False,
            'gdhsfguidfhgi': True,
            'form': NewCommentForm(),
            'zxcasjdlqwikjeo1i23' : True
    })
    

def gender_detail_f(request, gender, pk):
    if "gender" not in request.session:
        request.session["gender"] = ''
    request.session["gender"] = gender
    return redirect('item:detail', pk=pk)   

@login_required
def delete(request):
    request.user.items.clear()
    return redirect('item:basket')

@login_required
def purchase(request):
    purchase = Purchase.objects.create(user=request.user, telegram=request.POST['telegram'], price=0)
    price = 0
    if request.user.items.all():
        for item in request.user.items.all():
            price += item.price
            purchase.items.add(item)
        purchase.price = price  
        purchase.save()
        request.user.items.clear()


        context = {
            'purchase': purchase
        }
        template_name = "item/email_purchase.html"

        convert_to_html_content =  render_to_string(
            template_name=template_name,
            context=context
        )

        plain_message = strip_tags(convert_to_html_content)

        yo_send_it = send_mail(
            subject="Nyshki store",
            message=plain_message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[request.user.email],   # recipient_list is self explainatory
            html_message=convert_to_html_content,
            fail_silently=True
        )

        import requests

        bot_username = 'nyshaka_bot'
        bot_api = settings.BOT_API
        channel_name = '@nyashki_orders'
        message = f'заказ для telegram:{purchase.telegram}, price: {purchase.price}$, email {purchase.user.email}'
        url = f'https://api.telegram.org/bot{bot_api}/sendMessage?chat_id={channel_name}&text={message}'

        requests.get(url)

        return redirect('item:basket')
    return redirect('item:basket')

@login_required
def purchase_delete_admin(request, pk):
    if request.user.is_superuser:
        instance = Purchase.objects.get(id=pk)
        instance.delete()
        return render(request, 'item/purchases.html', {
            "purchases": Purchase.objects.all()
        })

@login_required
def purchase_delete(request, pk):
    instance = Purchase.objects.get(id=pk)
    context = {
        'purchase': instance
    }
    template_name = "item/email_delete.html"
    convert_to_html_content =  render_to_string(
        template_name=template_name,
        context=context
    )
    plain_message = strip_tags(convert_to_html_content)

    
    yo_send_it = send_mail(
        subject="Nyshki store",
        message=plain_message,
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email],   # recipient_list is self explainatory
        html_message=convert_to_html_content,
        fail_silently=True
    )
    
    import requests
    bot_username = 'nyshaka_bot'
    bot_api = settings.BOT_API
    channel_name = '@nyashki_orders'
    message = f'заказ для telegram:{instance.telegram}, price: {instance.price}$, email {instance.user.email}, УДАЛЕН'
    url = f'https://api.telegram.org/bot{bot_api}/sendMessage?chat_id={channel_name}&text={message}'
    requests.get(url)
    instance.delete()

    return redirect('item:basket')


@login_required
def all_purchases(request):
    if request.user.is_superuser:
        return render(request, 'item/purchases.html', {
            "purchases": Purchase.objects.all()
        })
    else:
        return redirect('/')
    

@login_required
def new_category(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            form = NewCategoryForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('/')
        else:
            form = NewCategoryForm()
        return render(request, 'item/new_category_form.html', {
            'form': form,
            'title': 'New Category',
            'gdhsfguidfhgi': True
        })
            
    else:
        return redirect('/')
    


@login_required
def new_item(request):
    if request.user.is_superuser:
        if request.method == 'POST':

item/templates/item/detail.html
{% extends 'core/base.html' %}
{% block title %}{{ item.name }}{% endblock %}


{% block content %}



<div class="grid grid-cols-1 md:grid-cols-2 gap-7 mt-4" id="xcvxckjvl123">

    <div class="md:ms-20">
        <a href="{% url 'item:detail' item.id %}">
            {% if item.gender == 'W'%}
                {% if item.image.url %}
                    <img src="{{ item.image.url }}" class="transition-transform duration-300 transform hover:scale-105 rounded-2xl object-contain w-full" id="detail-img">
                {% endif %}
            {% else %}
                {% if item.image.url %}
                    <img src="{{ item.image.url }}" class="transition-transform duration-300 transform hover:scale-105 rounded-2xl object-contain w-full" id="detail-img">
                {% endif %}
            {% endif %}
        </a>
    </div>

    <div class="weasfdasf me-5 px-10 py-4 bg-gray-100 rounded-xl dark:bg-zinc-500 dark:text-whitemd:me-20 transition-transform duration-300 transform hover:scale-105" id="centered">
        <hr class="dark:text-white">
        <p class="text-xl md:text-3xl dark:text-red-50 mt-4">{{ item.name }} - {{ item.category }}</p> <br>
        <p class="text-xl md:text-3xl dark:text-red-50">{{ item.description }}</p> <br>
        <p class="text-xl md:text-3xl dark:text-red-50 mb-4"> {% if item.gender == 'W' %} For Woman {% else %} For Man {% endif %}</p> <br>
        <p class="text-xl md:text-3xl dark:text-red-50"><strong>{{ item.price }}$ </strong></p>
        <hr class="dark:text-white">
    
        {% if not request.user.is_authenticated %}
            <a href="{% url 'item:add' item.id %}" class="block md:w-1/2 md:mx-auto text-center md:mt-6 mt-4 md:px-6 md:py-3 px-4 py-2 text-lg font-semibold bg-green-400 hover:bg-green-500 text-white rounded-xl">Add</a>
        {% else %}
            {% if in_basket %}
            <a href="{% url 'item:remove_detail' item.id %}" class="block md:w-1/2 md:mx-auto text-center md:mt-6 mt-4 md:px-6 md:py-3 px-4 py-2 text-lg font-semibold bg-red-600 hover:bg-red-500 text-white rounded-xl">Remove</a>
            {% else %}
            <a href="{% url 'item:add' item.id %}" class="block md:w-1/2 md:mx-auto text-center md:mt-6 mt-4 md:px-6 md:py-3 px-4 py-2 text-lg font-semibold bg-green-400 hover:bg-green-500 text-white rounded-xl">Add</a>
            {% endif %}
            {% if not request.user.is_superuser %}
                <a href="{% url 'conversation:new' item.id %}" class="block md:w-1/2 md:mx-auto text-center md:mt-6 mt-4 md:px-6 md:py-3 px-4 py-2 text-lg font-semibold bg-green-400 hover:bg-green-500 text-white rounded-xl">Contact admin</a>
            {% endif %}

        {% if operation == "add" %}
        <div class="alert alert-primary mt-4 text-center md:w-1/2 mx-auto" id="id01" role="alert">
            Добавлено
        </div>
        {%endif%}
        {% if operation == "remove" %}
        <div class="alert alert-danger mt-4 text-center md:w-1/2 mx-auto" id="id02" role="alert">
            Удалено
        </div> 
        {%endif%}

        {%endif%}

        {% if request.user.is_superuser %}
            <div class="grid md:grid-cols-2 grid-cols-1 gap-3 mt-4 w-3/4 mx-auto ">
                <a href="{% url 'item:remove_item' item.id %}" class="block text-center py-2 bg-red-500 hover:bg-red-600 text-white rounded-xl">Delete</a>
                <a href="{% url 'item:edit_item' item.id %}" class="block  text-center py-2 bg-red-500 hover:bg-red-600 text-white rounded-xl">Edit</a>
            </div>
        {%endif%}
    </div>
</div>

<div class="transition-transform duration-300 transform hover:scale-105 m-5 asdfklasfdfgdfg">
{% if request.user.is_authenticated %}
<h1 class="mb-2 text-3xl mt-12  dark:text-white text-center" id="{{op}}">Add comment</h1>

<form method="post" action="{% url 'item:new_comment'  item.id %}" enctype="multipart/form-data" class="asdzx222 mx-5 dark:text-white dark:bg-zinc-700 ">
    {% csrf_token %}

    <div class="space-y-4 text-center">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class=" mt-4 mb-3 p-6 bg-red-100 rounded-xl md:w-1/2 md:mx-auto dark:text-black">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}
    <div class="md:w-1/2 md:mx-auto"><button class="block w-3/4 mt-4 md:w-1/2 mx-auto text-center py-2 px-2 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button></div>
</form>
{%endif%}
</div>

{% if item.comments.all %}
<h1 class="mb-4 text-3xl mt-10 dark:text-white md:w-1/2 mx-auto text-center">Comments</h1>
<div class="space-y-6 md:w-1/2 mx-auto">
{% for comment in item.comments.all %}
    {%if op %}
    <div id="{{op}}" class="p-6 text-center {% if request.user == comment.user %} bg-sky-100 {% else %} bg-gray-100 dark:bg-zinc-500 dark:text-white{% endif %} rounded-xl">
    {%else%}
    <div class="p-6 text-center {% if request.user == comment.user %} bg-sky-100 {% else %} bg-gray-100 dark:bg-zinc-500 dark:text-white{% endif %} rounded-xl">
    {%endif%}
    <div {% if pk_comment == comment.id %} id="xdcfghjsdioufaos" {%endif%}>
        <p class="text-sm block">{{ comment.created_at }} </p>
    </div>
        <div>
            <div>
                <p class="text-3xl block">{{comment.user.username}} </p>
            </div>
            <div>
                <p class="mt-4 text-wrap text-xl">{{comment.description}}</p>
            </div>
        {% if request.user == comment.user %}
        <div class="grid md:grid-cols-2 grid-cols-1 gap-2 w-1/2 mx-auto mt-5">
            <a href="{% url 'item:edit_comment'  comment.id item.id %}" class="text-center py-2 bg-indigo-400 hover:bg-indigo-500 text-white rounded-xl">edit</a>
            <a href="{% url 'item:delete_comment'  comment.id item.id %}" class="text-center py-2 bg-indigo-400 hover:bg-indigo-500 text-white rounded-xl">delete</a>
        </div>
            {% if pk_comment == comment.id %}
            <form method="post" action="{% url 'item:edit_comment' comment.id item.id %}" enctype="multipart/form-data" class="mt-4">
                {% csrf_token %}
            
                <div class="space-y-4">
                    {{ edit_form.as_p }}
                </div>
            
                {% if edit_form.errors or edit_form.non_field_errors %}
        <div class=" mt-4 mb-3 p-6 bg-red-100 rounded-xl md:w-1/2 mx-auto dark:text-black">
            {% for field in edit_form %}
                {{ field.errors }}
            {% endfor %}

            {{ edit_form.non_field_errors }}
        </div>
    {% endif %}
            
                <div class="md:w-1/2 md:mx-auto"><button class="mt-2 w-3/4 text-center block md:w-1/2 mx-auto py-2 px-2 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
                </div>
            </form>
            {% endif %}
        {%endif%}
        </div>
    </div>  
{% endfor %}
</div>
{%endif%}

<div id="target-element"></div>
<div id="target-element"></div>

{% if related_items %}
<div class="mt-10 px-3 md:px-6 md:py-12 py-4 bg-gray-100 rounded-xl dark:bg-zinc-500 md:mx-20 transition-transform duration-300 transform hover:scale-105">
    <h2 class="mb-4 mb-8 text-3xl text-center font-bold dark:text-white">Related</h2>

    <div class="xcovixcopvi grid grid-cols-2 md:grid-cols-4 gap-8">
        {% for item in related_items %}
            <div class="transition-transform duration-300 transform hover:scale-105">
                <a href="{% url 'item:detail' item.id %}">
                    {% if item.gender == 'W'%}
                        {% if item.image.url %}
                            <img src="{{ item.image.url }}" class="zoom-image rounded-xl object-cover w-full md:h-96 h-60">
                        {% endif %}
                    {% else %}
                        {% if item.image.url %}
                            <img src="{{ item.image.url }}" class="zoom-image rounded-xl object-cover w-full md:h-96 h-60">
                        {% endif %}
                    {% endif %}
                    <div class="dfkjsdlkf p-3 bg-white rounded-b-xl md:text-center">
                            {% if item.gender == 'M'%}
                            <h2 class="md:text-3xl text-xl text-blue-700 font-semibold">{{ item.name }}</h2>
                            {% else %}
                            <h2 class="md:text-3xl text-xl text-red-700 font-semibold">{{ item.name }}</h2>
                            {% endif %}
                        <strong><p class="text-xl md:text-3xl font-semibold">{{ item.price }}$</p></strong>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{%endif%}


{% endblock %}

item/templates/item/edit_category_form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

<div id="s0ufsduf"></div>

<h1 class="mb-6 text-3xl mt-4 dark:text-white text-center">{{ title }}</h1>
<div class="mx-5 transition-transform duration-300 transform hover:scale-105 text-center">
<form method="post" action="{% url 'item:edit_category' category.id %}" enctype="multipart/form-data" class="dark:text-white">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl mx-auto w-1/2 dark:text-black mt-2">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
    
                {{ form.non_field_errors }}
            </div>
        {% endif %}

    <div class="md:mx-auto md:w-1/2">        <button class="block mt-3 w-3/4 md:w-1/2 mx-auto text-center py-2 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </div>
</form>
</div>
{% endblock %}

item/templates/item/edit_item_form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

<div id="21312awsdasdasd"></div>
<h1 class="mb-6 text-3xl mt-4 dark:text-white text-center">{{ title }}</h1>

<div class="mx-5 transition-transform duration-300 transform hover:scale-105 text-center">


    <form method="post" action="{% url 'item:edit_item' item.id %}" enctype="multipart/form-data" class="dark:text-white">
        {% csrf_token %}
    
        <div class="space-y-4">
            {{ form.as_p }}
        </div>
    
        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl mx-auto w-1/2 dark:text-black mt-2">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
    
                {{ form.non_field_errors }}
            </div>
        {% endif %}
    
        <div class="md:mx-auto md:w-1/2">        <button class="block mt-3 w-3/4 md:w-1/2 mx-auto text-center py-2 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </div>
    </form>


</div>
{% endblock %}